### ISSUE TITLE
Feature:  CLI artifact add command `rstuf artifact download` 

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#332]
### What is the task about?

This task is about creating the download feature for `rstuf artifact`

It should use the python-tuf ngclient. The [python-tuf client](https://github.com/theupdateframework/python-tuf/tree/develop/examples/client) example is a good reference implementation

## Download Artifact (Feature)

Note: The download feature ignores `rstuf --auth`, it uses the public metadata and the repository information. It doesn't use the RSTUF API.

### Settings
The `rstuf` command line has the `rstuf.ini` and it must be used for the download feature.
https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/9df308177620245cdbbbb401a1217a3e2d5df5bb/repository_service_tuf/cli/__init__.py#L63-L67

#### Trusted Root (`root`)

The user can configure the on the `rstuf.ini` the Metadata URL or use a parameter `-r/--root`
This is the path of the initial trusted root TUF Metadata

#### Metadata URL (`metadata_url`)

The user can configure the on the `rstuf.ini` the Metadata URL or use a parameter `-m/--metadata_url`
This is the URL where the python-tuf ngclient will check the metadata

#### Artifact Base URL (`artifact_url`)

The user can configure the on the `rstuf.ini` the Artifact Base URL or use a parameter `-a/--artifacts_url`
This URL is used to fetch the artifacts by the python-tuf ngclient
Example:

`rstuf artifact download project/file1.tar.gz`
The ngclient will use `http://downloads.example.com` as the artifact URL (target base URL)  and the path `project/file1.tar.gz`, fetching from `http://downloads.example.com/project/file1.tar.gz` when the target is valid.

####  Hash Prefix (`hash_prefix`)

The user can configure the on the `rstuf.ini` the `hash_prefix` True or False or use a parameter `--hash-prefix`
If the user uses --hash-prefix it becomes `True`

The default (if not configured also) is `False`

It is used to add the hash or not.
The above example (`rstuf artifact download --hash-prefix project/file1.tar.gz`) will become `http://downloads.example.com/project/<hash>-file1.tar.gz`
An example of this implementation is [available here](https://github.com/theupdateframework/python-tuf/blob/12d0c3cd1e168d07fcbccca8c774e658b5562a97/examples/client/client#L76)

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/334

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivanayov** [comment]
I'd like to work on this :)

**Comment by kairoaraujo** [comment]
The above design describe how to download using command line giving parameters

Here is my design for to implement (feature) using configuration file.

First, based on the abovementioned parameters, I would move from `.ini` to the `yaml` standard file, as it has better readability.

This is my design suggestion for the `rstuf.yaml` settings/configuration file.
Note: `server` entry is not part of this feature (`rstuf artifact download`), but `rstuf artifact upload` and `rstuf admin` commands

```yml
server: http://127.0.0.1

repositories:
  name1:
    artifact_base_url: <string>
    metadata_url: <string>
    trusted_root: <base64>
  name1:
    artifact_base_url: <string>
    metadata_url: <string>
    trusted_root: <base64>
    hash_prefix: <optional: boolean>

current_repository: <string>
```

An example:

```yaml
server: http://api.rstuf.org

repositories:
  rubygems:
    artifact_base_url: https://rubygems.com/downloads/
    metadata_url: https://metadata.rubygems.org
    trusted_root: <base64>
  pypi:
    artifact_base_url: https://files.pythonhosted.org/
    metadata_url: http://tuf.pypi.org
    trusted_root: <base64>
    hash_prefix: True

current_repository: rubygems
```

The user could download using:
`rstuf artifact download <artifact name>`

By default, the user will download using the `current_repository` defined.

I will add here some sub-features I think are very nice:

#### Show current repository
```shell
rstuf artifact download repository
```
Shows the `current_repository`

#### Show all configured repositories
```shell 
rstuf artifact download repository --all
```
Show all the configured repositories

#### Show all specific repository
```shell 
rstuf artifact download repository pypi
```
Show all the configured repositories

#### Switch current repository
```shell
rstuf artifact download repository use pypi
```
Switch `current_repository` to pypi

#### Set a new repository
```shell
rstuf artifact download repository set -n/--name cpan -m/--metadata_url https://rstuf.cpan.org -a/--artifacts_url https://metacpan.org/release/ -r/--root <file root.json or url https://rstuf.cpan.org/1.root.json>
```

#### Update a repository
```shell 
rstuf artifact download repository update  cpan -m/--metadata_url https://tuf.cpan.org
```
Note: Any value can be updated

#### Delete a repository
```shell 
rstuf artifact download repository delete  cpan
```

This is somehow inspired in kubectl
